# Client List
ISSUE_PRIORITY_HIGH = "C: Client A"
ISSUE_PRIORITY_MED = "C: Client B"
ISSUE_PRIORITY_LOW = "C: Client B"

ISSUE_PRIORITY_HIGH_STR = 'High Priority'
ISSUE_PRIORITY_MED_STR = 'Med Priority'
ISSUE_PRIORITY_LOW_STR = 'Low Priority'

ISSUE_PRIORITY_CHOICES = ((ISSUE_PRIORITY_HIGH, ISSUE_PRIORITY_HIGH_STR),
                         (ISSUE_PRIORITY_MED, ISSUE_PRIORITY_MED_STR),
                         (ISSUE_PRIORITY_LOW, ISSUE_PRIORITY_LOW_STR))




# Priority Options
ISSUE_PRIORITY_HIGH = "P: High Priority"
ISSUE_PRIORITY_MED = "P: Med Priority"
ISSUE_PRIORITY_LOW = "P: Low Priority"

ISSUE_PRIORITY_HIGH_STR = 'High Priority'
ISSUE_PRIORITY_MED_STR = 'Med Priority'
ISSUE_PRIORITY_LOW_STR = 'Low Priority'

ISSUE_PRIORITY_CHOICES = ((ISSUE_PRIORITY_HIGH, ISSUE_PRIORITY_HIGH_STR),
                         (ISSUE_PRIORITY_MED, ISSUE_PRIORITY_MED_STR),
                         (ISSUE_PRIORITY_LOW, ISSUE_PRIORITY_LOW_STR))

# Category Options
ISSUE_CATEGORY_BUG = "Bug"
ISSUE_CATEGORY_ENHANCEMENT = "Enhancement"
ISSUE_CATEGORY_REPORTING = "Reporting"
ISSUE_CATEGORY_SUPPORT = "OPS Support"

ISSUE_CATEGORY_BUG_STR = 'Bug'
ISSUE_CATEGORY_ENHANCEMENT_STR = 'Enhancement'
ISSUE_CATEGORY_REPORTING_STR = 'Reporting'
ISSUE_CATEGORY_SUPPORT_STR = 'OPS Support'

ISSUE_CATEGORY_CHOICES = ((ISSUE_CATEGORY_BUG, ISSUE_CATEGORY_BUG_STR),
                         (ISSUE_CATEGORY_ENHANCEMENT, ISSUE_CATEGORY_ENHANCEMENT_STR),
                         (ISSUE_CATEGORY_REPORTING, ISSUE_CATEGORY_REPORTING_STR),
                         (ISSUE_CATEGORY_SUPPORT, ISSUE_CATEGORY_SUPPORT_STR))

